---
# tasks file for sys.kubectl_el
- name: Update Packages
  yum: name=* state=latest
- name: Get the latest kubectl binary
  get_url:
    url:  https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
    dest: /home/{{ ansible_user }}
- name: move it to /usr/local/bin
  command: mv /home/{{ansible_user}}/kubectl /usr/local/bin

