---
# tasks file for sys.set_credentials
- name: Synchronize files between the master
  become: true
  synchronize:
    src: /home/{{ ansible_user }}/.kube/config
    dest: /home/{{ ansible_user }}/.kube/config
    mode: pull
  delegate_to: master
- name: Ensure alias is present
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "alias k='kubectl'"
    state: present
- name: Ensure completion is present
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: "source <( kubectl completion bash) | sed s/kubectl/k/g )"
    state: present
